### ISSUE TITLE
Add `!` versions of save and update

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/record#66]
Raise if it fails to save/update

```crystal
MyForm.save! params # Returns the record or raises if it fails to validate or save
MyForm.update! params # Returns the record or raises if it fails to validate or save
```

This would add a method to the `LuckyRecord::Form` called `self.save!` and `self.update!`. They would work similar to the non `!` methods, but would not accept a block. They would instead return the record.

**Comment by coderhs** [comment]
I would like to have a go at this feature. If no one else is working on it.

**Comment by paulcsmith** [comment]
@coderhs that would be great! Thanks!

**Comment by edwardloveall** [comment]
@coderhs Oh no! I must have started to work on this right after your comment and created #82. So sorry about that.

**Comment by coderhs** [comment]
@edwardloveall No issues. I haven't started on the task yet, so no harm done. On to the next issue. :)
