### ISSUE TITLE
Raise No record Found instead of Index out of bounds on find method

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/record#73]
On the queryable class the find method is implemented this way:
https://github.com/luckyframework/record/blob/d36e71a4bafb17c32982aacdc4cfee572f5dcdcb/src/lucky_record/queryable.cr#L31-L33

A simple code:
`UserQuery.new.find(id)`
Will generate:
```
ERROR: Index out of bounds (IndexError)
0x105fa9f95: *CallStack::unwind:Array(Pointer(Void)) at ??
0x105fa9f31: *CallStack#initialize:Array(Pointer(Void)) at ??
0x105fa9f08: *CallStack::new:CallStack at ??
0x105f92b85: *raise<IndexError>:NoReturn at ??
0x10614c38f: *Array(User)@Indexable(T)#first:User at ??
0x1061062a3: *UserQuery@LuckyRecord::Queryable(T)#first:User at ??
0x1061064be: *UserQuery@LuckyRecord::Queryable(T)#find<String>:User at ??
0x10615e28a: *Users::Show#before_action:(LuckyWeb::ActionCallbacks::Continue | LuckyWeb::Response) at ??
....
```
Would be better to raise a "No record found " error instead of getting a "Index out of bounds" because we are calling first on a empty array:

Like:
```crystal
 def find(id)
  if id(id).limit(1).size > 0
    id(id).limit(1).first 
  else
    raise "No record found"
  end
 end 
```

Is that ok?

**Comment by paulcsmith** [comment]
Yep, this is absolutely something that I'd like to do. I think it should raise a `RecordNotFoundError` error that should probably be defined in `src/lucky_record/errors.cr`

I also think we could do something like this:

```crystal
# the first? will return the record or nil
id(id).limit(1).first? || raise RecordNotFoundError.new
```

Thanks for suggesting this

**Comment by Xosmond** [comment]
@paulcsmith  i was trying to run crystal spec on a fork on this project to make a PR but im getting:
`Error in tasks.cr:2: while requiring "lucky_migrator": can't find file 'lucky_migrator'`

This lucky_migrator does not appear on shard.yml and I can't find it in other place.

**Comment by paulcsmith** [comment]
Did you run `shards install` to get the dependencies first? That may be the issue

**Comment by Xosmond** [comment]
Two things:
1. To run tests I need to have a migrated db, so I had to have `lucky_migrator` on shards.yml:
```yaml
   lucky_migrator:
     github: luckyframework/migrator
     version: ~> 0.2.3
```
After the install, the dependency doesnt matter, thats why you didnt got the error.
2. To create and migrate the db i had to have the db config on tasks.cr:
```crystal
# tasks.cr
...
database = "lucky_record_test"

LuckyRecord::Repo.configure do
  settings.url = LuckyRecord::PostgresURL.build(
    hostname: "localhost",
    database: database
  )
end

LuckyMigrator::Runner.configure do
  settings.database = database
end
...
```
After create and migrate the db, it doesn't matter to have that on tasks.cr, thats why you didnt got the db error.

Now I can run `crystal spec` without problems.

Do you want me to add this extra code on the PR for this issue?

**Comment by paulcsmith** [comment]
That would be wonderful if you could add that as part of the PR, but could you make it as a separate commit so it's easy to see that it is a separate thing. Or you could even create two separate PRs so it's easier to review.

Also, I think you can add lucky_migrator to `development_dependencies` in `shard.yml` so it is only needed in dev, but won't be needed when people install lucky_record. See example here: https://github.com/crystal-lang/shards#usage

**Comment by Xosmond** [comment]
Sure, I will.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/record/pull/75
