### ISSUE TITLE
Add `allow_virtual`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/record#76]
https://gist.github.com/paulcsmith/59d578f5e20087240913f0a84b743a0d

This should get the param from the params. The value needs to be casted though so you can use types other than string. Either that or maybe the first version can only do strings and you have to manually cast to other types yourself: `my_virtual_number.value.to_i`. Maybe that's a decent solution for now...

**Comment by jdbann** [comment]
The `VirtualField` module in the gist is currently responding with:

```
instance variable '@_password_confirmation' of UserForm must be (LuckyRecord::Field(String) | Nil), not LuckyRecord::Field(String | Nil)
```

Adjusting line 10 to ` @_{{ name }} ||= LuckyRecord::Field(String).new(` still responds with:

```
17:44:58 web.1      |  no overload matches 'LuckyRecord::Field(String).new', name: Symbol, param: (String | Nil), value: (String | Nil), form_name: String
17:44:58 web.1      |  Overloads are:
17:44:58 web.1      |   - LuckyRecord::Field(T).new(name : Symbol, param : String | ::Nil, value : T, form_name : String)
17:44:58 web.1      |  Couldn't find overloads for these types:
17:44:58 web.1      |   - LuckyRecord::Field(String).new(name : Symbol, param : Nil, value : Nil, form_name : String)
17:44:58 web.1      |   - LuckyRecord::Field(String).new(name : Symbol, param : String, value : Nil, form_name : String)
```

Form and page code here for reference: https://gist.github.com/jdbann/5c16705c49155877f7450bebb944b787

**Comment by paulcsmith** [comment]
You need to change that to look like this: https://github.com/luckyframework/record/pull/86/files#diff-62686297c2233162f75476985a7c7a71R3

Because the LuckyRecord::Field is now `String?` and not `String` so the instance var needs to reflect that. I'm about to merge in PR #86 so you can likely use that and it will work just right 👍

**Comment by jdbann** [comment]
Works a treat 🎉
